# Generated by Django 3.1.7 on 2021-10-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210623_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='User',
            old_name='date_joined',
            new_name='created_at'
        )
    ]
