# Generated by Django 3.1.7 on 2021-04-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pve_comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterstage',
            name='uploaded_image',
        ),
    ]
