# Generated by Django 3.1.7 on 2021-05-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pve_comp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterstage',
            old_name='username',
            new_name='user',
        ),
    ]
