# Generated by Django 3.1.7 on 2021-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pve_comp', '0002_auto_20210414_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapterstage',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterstage',
            name='stage',
        ),
    ]
