# Generated by Django 3.1.7 on 2021-04-25 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pve_comp', '0002_chapterstage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='章'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ステージ'),
        ),
    ]
