# Generated by Django 3.1.7 on 2021-04-20 14:32

from django.db import migrations, models
import django.utils.timezone
import pve_comp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pve_comp', '0002_remove_chapterstage_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterstage',
            name='uploaded_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=pve_comp.models.rename_to_uuid),
            preserve_default=False,
        ),
    ]
