# Generated by Django 3.1.7 on 2021-04-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pve_comp', '0003_auto_20210419_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterstage',
            name='chapter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pve_comp.chapter'),
        ),
        migrations.AddField(
            model_name='chapterstage',
            name='stage_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pve_comp.stage'),
        ),
    ]
