# Generated by Django 4.0 on 2022-01-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relic_calculator', '0002_relic_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Relic',
            old_name='compornent1',
            new_name='component1'
        ),
        migrations.RenameField(
            model_name='Relic',
            old_name='compornent2',
            new_name='component2'
        ),
        migrations.RenameField(
            model_name='Relic',
            old_name='compornent3',
            new_name='component3'
        ),
        migrations.RenameField(
            model_name='Relic',
            old_name='compornent4',
            new_name='component4'
        ),
    ]
